//This source code is generated by UI Designer Studio.

#ifndef UIFLOWWNDUSBRES_H
#define UIFLOWWNDUSBRES_H

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIDisplayUtil.h"
//------------------------------------------------------------

SHOW_ITEM_RECT(CMD_Rectangle,Skin1Rect,0,0,479,271,0,0,14,14,0,0,0)
SHOW_MAP_BEGIN(Skin1)
SHOW_MAP_BODY(Skin1Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin1,0,0,479,271)

SHOW_ITEM_RECT(CMD_Rectangle,Skin3Rect,0,0,479,79,0,0,14,14,0,0,0)
SHOW_MAP_BEGIN(Skin3)
SHOW_MAP_BODY(Skin3Rect)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Skin3,0,0,479,79)

SHOW_ITEM_TEXT(CMD_Text|CMD_ITEM,Text5,6,6,467,69,STRID_NULL,0,0,0,0,2,1,1,256,0,17,0,0,0,0)
SHOW_MAP_BEGIN(Normal2)
SHOW_MAP_BODY(Skin3)
SHOW_MAP_BODY(Text5)
SHOW_MAP_END

SHOW_ITEM_GROUP(CMD_Group,Normal2,0,100,479,179)

SHOW_MAP_BEGIN(UIFlowWndMSDC_StaticTxt_MassStorage)
SHOW_MAP_BODY(Normal2)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndMSDC_StaticTxt_MassStorage)
CREATE_STATIC_DATA(UIFlowWndMSDC_StaticTxt_MassStorage,STRID_MSDC)
CREATE_STATIC_CTRL(UIFlowWndMSDC_StaticTxt_MassStorage,0,0,100,479,179)

//@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

SHOW_MAP_BEGIN(UIFlowWndUSB)
SHOW_MAP_BODY(Skin1)
SHOW_MAP_END

DECLARE_EVENT(UIFlowWndUSB)
DECLARE_CTRL_LIST(UIFlowWndUSB)
CREATE_CTRL(UIFlowWndUSB,UIFlowWndUSB,CTRL_WND,NULL,0 ,0,0,479,271)
#endif
